name: chair-retrieval

category: 03001627
split: train
phase: train_retrieval
 
mesh_dir: data/shapenet/shape_data
split_file: data/shapenet_split/partnet.csv
log_dir: logs
 
n_keypoints: 12
ckpt: 
ico_recon: true